#!/usr/bin/env bash
# avk-idle-convergence-test.sh — M4C.3H: a settled compositor stops repainting.
#
# THE INVARIANT
#
#   A visually stable compositor state must converge to ZERO self-generated
#   repaint work.
#
# Not "less repaint work". Zero. Once every animation has finished and no
# client has committed anything, the compositor must generate no further
# frames of its own.
#
# WHAT BROKE IT
#
# wlr_scene_rect_set_gradient() had no identical-write check, and it is reached
# from the per-frame path:
#
#     rendermon -> client_draw_frame -> client_apply_focus_opacity
#       -> client_set_border_fill          (every frame, for the FOCUSED
#          -> wlr_scene_rect_set_gradient    window, animating or not)
#          -> scene_node_update -> damage -> another frame is needed
#
# so a focused window with `border_gradient 1` re-damaged itself forever. Every
# sibling setter in that file already held the line -- set_color() memcmp()s,
# set_corner_radii() compares through fx_corner_radii_eq(), set_size() compares
# its ints -- and the comment above client_apply_focus_opacity's caller already
# ASSERTED the invariant ("set_border_fill are dirty-checked, so this is a
# no-op when unchanged"). It was true of one branch and false of the other.
#
# IT WAS NEVER AN ANIMATION-TERMINATION BUG, which is the obvious hypothesis
# and the wrong one. The focus animation is duration-based on a wall clock
# (passed_time / duration, terminal at >= 1.0) with no asymptotic
# interpolation anywhere, and animation_duration_focus DEFAULTS TO 0 -- which
# completes on the first tick. The frames came from the settled branch that
# runs after the animation is over, not from an animation that never ended.
#
#   CASE=idle       gradient border, quiet client -> zero self-generated frames
#   CASE=animate    focus really animates, and really stops
#   CASE=solid      no regression with a solid border
#   CASE=off        no regression with gradients disabled
#
#   BREAK=gradient-noop-damage   removes the check. MUST FAIL.
set -u

. "$(dirname "$0")/lib/headless.sh"

CURRENT_TEST="avk-idle-convergence"
BREAK="${BREAK:-}"
CASES="${CASES:-idle animate solid off}"

REPAINT="$(dirname "$0")/wlrepaint/wlrepaint"
[ -x "$REPAINT" ] || { echo "not built -- run: cd contrib/wlrepaint && make" >&2; exit 1; }

# Every query goes through a timeout. Under the break the compositor's event
# loop never returns to its clients, so an untimed amsg blocks forever and the
# suite hangs instead of failing -- which is the difference between a red test
# and a wedged machine.
# 4s, not 8: under the break every one of these burns its full timeout while
# the compositor allocates ~140 MB/s, so the length of this call is the length
# of the leak the break run has to survive.
gt() { ASTEROIDZ_INSTANCE_SIGNATURE="$HL_SIG" timeout 4 amsg $* 2>/dev/null; }

# An amsg that times out produces NO OUTPUT, and jq's `// "TIMEOUT"` fallback
# never fires because jq is handed an empty stream -- it emits nothing too. The
# first version of this returned "" there, so `$F2 != "TIMEOUT"` was true and
# the starvation assertion PASSED under the break, and `$((F2 - F1))` on two
# empty strings evaluated to 0 and the convergence assertion passed with it.
# Both headline assertions came back green on a compositor that was wedged and
# leaking half a gigabyte. The emptiness has to be caught here, once.
frames() {
	local out
	out=$(gt get avk-stats | jq -r '.frames // empty' 2>/dev/null)
	case "$out" in
		''|*[!0-9]*) echo TIMEOUT ;;
		*) echo "$out" ;;
	esac
}

# hl_wait_client_count() goes through the library's UNTIMED amsg, so under the
# break it blocks forever and the suite hangs before reaching a single
# assertion -- a wedged machine where a red test belongs. This is the same wait
# with a bound on it. Returns non-zero if the clients never appeared, and the
# assertions below then run and fail, which is the point.
wait_clients() { # wait_clients <n> [tries]
	local n="$1" tries="${2:-12}" got
	for _ in $(seq 1 "$tries"); do
		got=$(gt get all-clients | jq -r '.clients|length' 2>/dev/null)
		[ "${got:-0}" = "$n" ] && return 0
		sleep 1
	done
	echo "  (clients never reached $n -- last saw ${got:-none})"
	return 1
}

start() { # start <gradient 0|1> <duration_ms>
	OUTDIR="${TMPDIR:-/tmp}/asteroidz-idle-$1-$2-$$"
	HL_OUTDIR="$OUTDIR"
	HL_ENV=""
	[ "$BREAK" = gradient-noop-damage ] && \
		HL_ENV="$HL_ENV AZ_GRADIENT_NOOP_DAMAGE=1"
	export HL_OUTDIR HL_ENV
	hl_start "border_radius 0
borderpx 16
focuscolor 0xff0000ff
bordercolor 0x2f6fd0ff
border_gradient $1
border_gradient_angle 45
border_gradient_color2 0x00ff00ff
animations $([ "$2" -gt 0 ] && echo 1 || echo 0)
animation_duration_focus $2
shadows 0
layer_shadows 0
effects { blur { enable 0 } }
layout {
    titlebar { enable 0 }
}"
	sleep 2
}

# One client that paints ONCE and then goes quiet (--frames 1). Every frame
# after that is one the compositor generated by itself, which is the entire
# measurement -- a client repainting continuously would supply frames of its
# own and the number would mean nothing.
spawn_quiet() { # spawn_quiet <name> <colour>
	"$REPAINT" --title "$1" --size 500x350 --solid "$2" --frames 1 --ssd \
		--hold-ms 100 > "$OUTDIR/$1.log" 2>&1 &
	HL_SPAWNED_PIDS+=("$!")
}

# ── idle: the invariant itself ──────────────────────────────────────────────
case_idle() {
	echo
	echo "--- gradient border, nothing moving: zero self-generated frames ---"
	start 1 0
	spawn_quiet idle1 202020
	wait_clients 1 || true
	sleep 4

	# PREMISE: there is a focused window, so the per-frame border path is
	# actually being exercised. Without a focused client this converges
	# trivially and proves nothing.
	FOC=$(gt get focused-client | jq -r '.title // "none"')
	hl_assert "a window is focused, so the border path runs (premise: $FOC)" \
		"$([ "$FOC" = "idle1" ] && echo true || echo false)" "true"

	F1=$(frames); R1=$(awk '/VmRSS/{print $2}' /proc/"$HL_COMP_PID"/status 2>/dev/null)
	sleep 5
	F2=$(frames); R2=$(awk '/VmRSS/{print $2}' /proc/"$HL_COMP_PID"/status 2>/dev/null)
	echo "  frames $F1 -> $F2 over 5s idle;  rss ${R1} -> ${R2} kB"

	# THE ASSERTION. Under the break this is a TIMEOUT rather than a number,
	# which is itself the failure -- so it is checked explicitly instead of
	# being allowed to arithmetic its way to something plausible.
	ANSWERED=$([ "$F1" != TIMEOUT ] && [ "$F2" != TIMEOUT ] && echo true || echo false)
	hl_assert "avk-stats answered at all (no IPC starvation; got '$F1' -> '$F2')" \
		"$ANSWERED" "true"
	# Asserted unconditionally. Skipping it when the query failed is how a
	# wedged compositor scores a clean convergence result.
	hl_assert "the settled compositor generated 0 frames in 5s" \
		"$([ "$ANSWERED" = true ] && [ "$((F2 - F1))" -eq 0 ] && echo true || echo false)" "true"
	# Heap growth is the same loop seen from the other side: ~54 MB/s when it
	# spins, flat when it does not.
	if [ -n "${R1:-}" ] && [ -n "${R2:-}" ]; then
		hl_assert "the heap did not grow while idle ($((R2 - R1)) kB in 5s)" \
			"$([ "$((R2 - R1))" -lt 2048 ] && echo true || echo false)" "true"
	fi

	# The gradient is still DRAWN and still a ramp -- a check that suppressed
	# every write into oblivion would also converge to zero frames.
	DRAWS=$(gt get avk-stats | jq -r '.gradient_draws // 0')
	hl_assert "the gradient is still being drawn ($DRAWS draws)" \
		"$([ "${DRAWS:-0}" -gt 0 ] && echo true || echo false)" "true"
	grim -o HEADLESS-1 "$OUTDIR/idle.png" 2>/dev/null
	SPREAD=$(python3 - "$OUTDIR/idle.png" <<'PY'
import sys
from PIL import Image
im = Image.open(sys.argv[1]).convert('RGB'); px = im.load(); W, H = im.size
lo = [255]*3; hi = [0]*3; seen = 0
for y in range(0, H, 2):
    for x in range(0, W, 2):
        r, g, b = px[x, y]
        # the border ramps red -> green; ignore wallpaper and the grey client
        if r > 60 and b < 90 and abs(r - g) < 250:
            seen += 1
            for i, v in enumerate((r, g, b)):
                lo[i] = min(lo[i], v); hi[i] = max(hi[i], v)
print(max(hi[i] - lo[i] for i in range(3)) if seen > 50 else 0)
PY
)
	hl_assert "and it is still a RAMP, not a flat fill (channel spread $SPREAD)" \
		"$([ "${SPREAD:-0}" -gt 100 ] && echo true || echo false)" "true"
	hl_stop
}

# ── animate: it must still animate, and must still stop ─────────────────────
case_animate() {
	echo
	echo "--- focus animation runs, then settles ---"
	start 1 400
	spawn_quiet anim1 202020; sleep 2
	spawn_quiet anim2 203020
	wait_clients 2 || true
	sleep 4

	A=$(frames); sleep 2; B=$(frames)
	hl_assert "before any switch, the scene is already settled (got '$A' -> '$B')" \
		"$([ "$A" != TIMEOUT ] && [ "$B" != TIMEOUT ] && [ "$((B - A))" -eq 0 ] && echo true || echo false)" "true"

	animated=0; settled=0; moved=0
	for n in 1 2 3 4; do
		case $((n % 2)) in 1) DIR=left ;; 0) DIR=right ;; esac
		W0=$(gt get focused-client | jq -r '.title // "none"')
		A=$(frames)
		gt dispatch focus_direction,$DIR >/dev/null
		sleep 1
		B=$(frames); W1=$(gt get focused-client | jq -r '.title // "none"')
		sleep 3
		C=$(frames)
		# PREMISE PER SWITCH. "+0 frames" from a dispatch that moved nothing
		# looks exactly like a settled animation. The first version of this
		# always sent `left`, so switches 2..4 moved nothing and reported a
		# perfectly settled compositor that had not been asked to do anything.
		if [ "$W0" = "$W1" ] || [ "$W1" = none ]; then
			echo "  switch $n ($DIR): focus did not move ($W0) -- not evidence"
			continue
		fi
		moved=$((moved + 1))
		echo "  switch $n ($DIR): $W0 -> $W1, +$((B - A)) frames animating, +$((C - B)) in the next 3s"
		[ "$((B - A))" -gt 0 ] && animated=$((animated + 1))
		[ "$((C - B))" -eq 0 ] && settled=$((settled + 1))
	done
	hl_assert "every focus switch moved focus (premise: $moved of 4)" \
		"$([ "$moved" -eq 4 ] && echo true || echo false)" "true"
	hl_assert "every switch actually animated ($animated of $moved)" \
		"$([ "$animated" -eq "$moved" ] && echo true || echo false)" "true"
	hl_assert "and every one settled to zero afterwards ($settled of $moved)" \
		"$([ "$settled" -eq "$moved" ] && echo true || echo false)" "true"

	# Responsiveness under rapid switching -- the symptom users would report.
	S=$(date +%s%N)
	for n in 1 2 3 4 5 6; do gt dispatch focus_direction,left >/dev/null; done
	MS=$(( ($(date +%s%N) - S) / 1000000 ))
	echo "  six IPC dispatches during focus churn: ${MS}ms total"
	hl_assert "IPC stays responsive under rapid focus changes (${MS}ms for 6)" \
		"$([ "$MS" -lt 2000 ] && echo true || echo false)" "true"

	# The animated gradient writes new colours every tick, so UPLOADS are
	# expected. Vulkan OBJECT allocation is not.
	GROWS=$(gt get avk-stats | jq -r '.gradient_buffer_grows // 0')
	UPLOADS=$(gt get avk-stats | jq -r '.gradient_buffer_uploads // 0')
	echo "  gradient buffer: $UPLOADS uploads, $GROWS growths"
	hl_assert "an animated gradient reallocated no buffer ($GROWS growths)" \
		"$([ "${GROWS:-1}" -eq 0 ] && echo true || echo false)" "true"
	hl_stop
}

# ── solid / off: the paths that were never broken must stay unbroken ────────
case_converges() { # case_converges <label> <gradient 0|1>
	echo
	echo "--- $1: still converges ---"
	start "$2" 0
	spawn_quiet conv1 202020
	wait_clients 1 || true
	sleep 4
	A=$(frames); sleep 4; B=$(frames)
	echo "  frames $A -> $B over 4s idle"
	hl_assert "$1: settled compositor generates 0 frames (got '$A' -> '$B')" \
		"$([ "$A" != TIMEOUT ] && [ "$B" != TIMEOUT ] && [ "$((B - A))" -eq 0 ] && echo true || echo false)" "true"
	hl_stop
}

for c in $CASES; do
	case "$c" in
		idle)    case_idle ;;
		animate) case_animate ;;
		solid)   case_converges "solid border" 0 ;;
		off)     case_converges "gradients disabled" 0 ;;
		*) echo "unknown case $c" >&2; exit 1 ;;
	esac
done
hl_summary
