#ifndef ASTEROIDZ_CONFIG_SOURCE_H
#define ASTEROIDZ_CONFIG_SOURCE_H

/* Where each config value came from, recorded as it is applied.
 *
 * A settings UI needs this for three separate reasons, and none of them can be
 * answered after the fact:
 *
 *   1. To WRITE a value back, you have to edit the declaration that is
 *      actually in force. `source` is applied in place (see parse_option's
 *      source branch), so a key set in config.kdl and again in a sourced
 *      colors.kdl is won by colors.kdl -- but config_files[] is in the order
 *      files were OPENED, which puts config.kdl first. Scanning that list and
 *      writing to the first file that mentions the key produces an edit that is
 *      immediately overruled by a file the user cannot see from the panel.
 *
 *   2. To refuse to write a value the compositor does not own. colors.kdl is
 *      regenerated by matugen on every wallpaper change; an edit there is lost
 *      at the next change, silently.
 *
 *   3. To tell the user WHY a control is showing what it is showing. "This
 *      comes from colors.kdl line 12" is the difference between a settings app
 *      and a settings app you distrust.
 *
 * Recorded as it happens because it is not derivable. The parse order is the
 * only account of who won, and nothing else keeps it.
 *
 * Spans are byte offsets rather than pointers on purpose: parse_config_file
 * frees the file text as soon as the document is parsed, and the writer re-reads
 * the file anyway. Offsets survive that; pointers would not.
 */

#include "kdl.h"

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

typedef struct {
	/* Copied, not interned. kdl_leaf falls back to `node->name` when a path has
	 * no canonical key, and kdl_free releases that string the moment the
	 * document is done with -- an interned pointer would dangle for exactly the
	 * ~190 keys that rely on the fallback. */
	char key[64];
	int32_t file; /* index into config_files[], or -1 for a runtime change */
	int32_t line;
	size_t span_start, span_end; /* the whole node                          */
	size_t val_start, val_end;   /* just its arguments                      */
	char path[160];              /* the path it was ACTUALLY written at,
								  * which is often not the canonical one --
								  * this config spells a top-level key as
								  * `misc { border_radius 9 }`              */
} ConfigOrigin;

#define CONFIG_ORIGIN_MAX 512

static ConfigOrigin config_origins[CONFIG_ORIGIN_MAX];
static int32_t nconfig_origins;

/* The node being applied right now.
 *
 * A static rather than a parameter threaded through parse_option: that function
 * is reached from a dozen callers (the KDL walker, the rule handlers, the legacy
 * `key=value` line reader, `dispatch set_option` at runtime) and most of them
 * have nothing useful to say about provenance. One hook at the top of
 * parse_option catches every one of them, and the ones that know more set this
 * first. Config parsing is single-threaded and non-reentrant except through
 * `source`, which saves and restores it. */
static struct {
	int32_t file;
	const KdlNode *node;
	const char *path;
	bool active;
} config_src_ctx = {.file = -1};

static void config_source_reset(void) {
	nconfig_origins = 0;
	config_src_ctx.file = -1;
	config_src_ctx.node = NULL;
	config_src_ctx.path = NULL;
	config_src_ctx.active = false;
}

/* Note that `key` was just set. Last writer wins, which is the same rule the
 * parser itself follows. */
static void config_source_note(const char *key) {
	if (!key || !*key)
		return;
	ConfigOrigin *o = NULL;
	for (int32_t i = 0; i < nconfig_origins; i++) {
		if (!strcmp(config_origins[i].key, key)) {
			o = &config_origins[i];
			break;
		}
	}
	if (!o) {
		if (nconfig_origins >= CONFIG_ORIGIN_MAX)
			return;
		o = &config_origins[nconfig_origins++];
		snprintf(o->key, sizeof(o->key), "%s", key);
	}

	if (config_src_ctx.active && config_src_ctx.node) {
		const KdlNode *n = config_src_ctx.node;
		o->file = config_src_ctx.file;
		o->line = n->span.line;
		o->span_start = n->span.start;
		o->span_end = n->span.end;
		o->val_start = n->span.name_end;
		o->val_end = n->span.args_end;
		snprintf(o->path, sizeof(o->path), "%s",
				 config_src_ctx.path ? config_src_ctx.path : "");
	} else {
		/* Changed in memory and not on disk -- `dispatch set_option`, or a
		 * default that override_config coerced. Invisible before this. */
		o->file = -1;
		o->line = 0;
		o->span_start = o->span_end = 0;
		o->val_start = o->val_end = 0;
		o->path[0] = '\0';
	}
}

/* Point a key's provenance at a node in a named file, explicitly.
 *
 * For the write path. After a batch is committed the values are re-applied in
 * memory, and going through parse_option's hook with no context recorded them as
 * `runtime` -- so `get config` reported "changed in memory, will not survive a
 * reload" about a value that had just been written to disk. Worse, the next
 * removal of that key then saw no file provenance and skipped the file edit
 * entirely, leaving the declaration behind while reporting success. */
static void config_source_note_at(const char *key, int32_t file,
								  const KdlNode *node, const char *path) {
	const KdlNode *prev_node = config_src_ctx.node;
	const char *prev_path = config_src_ctx.path;
	int32_t prev_file = config_src_ctx.file;
	bool prev_active = config_src_ctx.active;
	config_src_ctx.node = node;
	config_src_ctx.path = path;
	config_src_ctx.file = file;
	config_src_ctx.active = node != NULL;
	config_source_note(key);
	config_src_ctx.node = prev_node;
	config_src_ctx.path = prev_path;
	config_src_ctx.file = prev_file;
	config_src_ctx.active = prev_active;
}

/* Drop a key's provenance, so it reads as the compiled-in default again.
 *
 * For a removal: the declaration is gone from the file, and leaving an origin
 * behind would have `get config` naming a line that no longer holds it -- which
 * a settings app would then edit. */
static void config_source_forget(const char *key) {
	for (int32_t i = 0; i < nconfig_origins; i++) {
		if (strcmp(config_origins[i].key, key))
			continue;
		config_origins[i] = config_origins[nconfig_origins - 1];
		nconfig_origins--;
		return;
	}
}

static const ConfigOrigin *config_source_of(const char *key) {
	if (!key)
		return NULL;
	for (int32_t i = 0; i < nconfig_origins; i++)
		if (!strcmp(config_origins[i].key, key))
			return &config_origins[i];
	return NULL;
}

/* ---------- file ownership ---------- */

/* A config file the compositor must not rewrite.
 *
 * Decided per FILE, not per key. The alternative -- flagging the nine palette
 * keys matugen happens to write today -- is a list that is wrong the moment
 * someone adds a tenth, and says nothing at all about a generator nobody here
 * has heard of. A file that declares itself generated is self-describing and
 * keeps working.
 *
 * Two markers already exist in the wild and neither was designed for this, so
 * both are recognised and documented rather than replaced:
 *
 *   matugen                "! Auto-generated file. Do not edit directly."
 *   the display plugin     "Managed by the waybar-display plugin"
 *
 * New generators should write `asteroidz:generated-by <tool>` in a comment on
 * one of the first few lines.
 *
 * `output` blocks are the deliberate exception, handled by the caller rather
 * than here: output_persist has always written monitors.kdl, and that marker
 * means "no human maintains this", not "nobody may write". A settings UI
 * changing a scale is the compositor managing its own state; the same UI
 * rewriting a matugen palette is throwing away someone else's work. */
static bool config_file_is_foreign(const char *path, char *why, size_t whylen) {
	if (!path || !*path)
		return false;
	FILE *f = fopen(path, "rb");
	if (!f)
		return false;
	/* Only the head: a marker is a header, and a phrase appearing halfway down
	 * a hand-written file is a sentence about generated files, not a claim to
	 * be one. */
	char head[2048];
	size_t n = fread(head, 1, sizeof(head) - 1, f);
	head[n] = '\0';
	fclose(f);

	struct {
		const char *needle;
		const char *reason;
	} markers[] = {
		{"asteroidz:generated-by", "generated-file"},
		{"Auto-generated file. Do not edit directly", "matugen"},
		{"Managed by the waybar-display plugin", "display-plugin"},
	};
	for (size_t i = 0; i < sizeof(markers) / sizeof(markers[0]); i++) {
		if (strstr(head, markers[i].needle)) {
			if (why)
				snprintf(why, whylen, "%s", markers[i].reason);
			return true;
		}
	}
	if (why && whylen)
		why[0] = '\0';
	return false;
}

#endif /* ASTEROIDZ_CONFIG_SOURCE_H */
